spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  rabbitmq:
      host: duckbill.rmq.cloudamqp.com
      username: lshnmkvr
      virtual-host: lshnmkvr
      password: 5xns2ZvJ7KGCLM_VFj9cbA7hdsBEtTj9

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
